export const LOGIN_MODAL = 'LOGIN_MODAL';
export const SIGNUP_MODAL = 'SIGNUP_MODAL';
export const ADD_PRODUCT_MODAL = 'ADD_PRODUCT_MODAL';
export const DELETE_WARNING_MODAL = 'DELETE_WARNING_MODAL';
export const EDIT_PRODUCT_MODAL = 'EDIT_PRODUCT_MODAL';
